version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_NAME: jbn_furniture
      SIGN_KEY: secret
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
